jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi

      - name: install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          ndk: 26.1.10909125
          cmake: 3.22.1
          cache: gradle

      - name: install frontend dependencies
        run: bun install

      - name: build Android APK
        working-directory: src-tauri/gen/android
        run: ./gradlew assembleDebug